SELECT LANGILE.ID, LANGILE.IZENA, BULEGARI.ID_LANPOSTU FROM LANGILE INNER JOIN BULEGARI ON LANGILE.ID = BULEGARI.ID;

UPDATE LANGILE INNER JOIN BULEGARI ON LANGILE.ID = BULEGARI.ID SET LANGILE.SOLDATA = 30000;

SELECT ID FROM LANPOSTU